branches:
  - release
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - "@semantic-release/npm"
    - pkgRoot: .
  - - "@semantic-release/npm"
    - pkgRoot: releases/bundled
  - - "@semantic-release/npm"
    - pkgRoot: releases/esnext
  - '@semantic-release/github'
