branch: master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - path: '@qiwi/semantic-release-gh-pages-plugin'
    branch: 'gh-pages'
    dst: '.'
    msg: 'docs: update to v{{=it.nextRelease.gitTag}}'
    src: 'docs'
