language: node_js

os: linux

node_js: node

before_deploy: npm run build
deploy:
  provider: npm
  email: tom.vycital@gmail.com
  api_key:
    secure: W6lDh+YztE3fdgEk8PHdUfWrJ4j5VKC7BjXiuRiS8OxRRME3m4vB/SD23v9Rm9jc8EQRw+sYp16znbLPGo8ZACh4CZsMwRaOM+dcp0wTtEtGvH1vfbaXmiVx6LMYHqYKhydj4oGYUmOZAIWK8eqkSnqcsHHplKxQo6xaOqVKkPWVd5qrclaYwP7a2pYIyE/Hh0x0/6p0gaL4M0lQttbd6aGsIUW4AKGs/Ng0AEs/nWuJSZb7lguX3/uys/222hNANLTooudwxlhZpT4taNjq3iWGKn4tfh2MnhyoRoyv83isGGhay2w5JEG/RfKKlg4/Z/z8mm+igmF9sFooNA1u2Bfs6yJ7W4BezbdFPBzWAgDVEBZ64Z24rbB/7ZpoSWInL8lXSDKSK+N3o3jNFuV5h7uQITzUdxNvFWeHk5ZNtAeU5uWDEqN7+oyHN8hx9i7vxy6cvAF9cUO0bwfUY82XPh0mtrP8M4mSELOm/Uraj3LZ/oJSwNcAX9pg9KKOm+eLFZ2+kdKTPlf35+yj/M2YoSiVvifyepjBjUUUbn5GaI4lU/HLKdmxnhmbAVqXTz4nazyGXD5NbPGvj9fh9ArKF6XGZJAJaMS7SXnAwTCAxkSh6BGjmWnKiu4TxRRN9ZigTXeqJrd0YNiybfORL8wgJJM/Lz70GTMIDCWEU+ciCBs=
  tag: next
