# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:21.7.2
    working_directory: ~/repo

jobs:
  prepare:
    executor: node

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - '*'

  build:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run build

      - run: npm run check

      - persist_to_workspace:
          root: .
          paths:
            - 'dist'
            - 'docs'
            - 'releases'

  lint:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run: npm run lint

  test:
    executor: node

    steps:
      - attach_workspace:
          at: .

      # Test Renovate updated package versions (i.e. latest)
      - run: npm run test

      # Test various older versions
      - run: npm run test:versions

  gh_pages:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prepare Git
          command: |
            git config user.email "$GIT_EMAIL"
            git config user.name "$GIT_NAME"

      - run:
          name: Publish
          command: |
            npx gh-pages --dist 'docs' --message 'docs: update' --dotfiles --repo "https://$GH_USERNAME:$GH_TOKEN@github.com/Thomaash/vuex-ltm.git"

  release:
    executor: node

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prepare NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: Prepare Git
          command: |
            git config user.email "tom.vycital@gmail.com"
            git config user.name "Tomáš Vyčítal"
      - run:
          name: Release
          command: |
            npx semantic-release

workflows:
  version: 2

  build:
    jobs:
      - prepare

      - build:
          requires:
            - prepare

      - lint:
          requires:
            - prepare

      - test:
          requires:
            - prepare

      - gh_pages:
          requires:
            - prepare
            - build
            - lint
            - test
          filters:
            branches:
              only:
                - release

      - release:
          requires:
            - prepare
            - build
            - lint
            - test
          filters:
            branches:
              only:
                - release
